version: '3.8'
services:
  traefik-proxy:
    image: traefik:v3.0.0-beta2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.postgres.address=:5432" # PostgreSQL endpoint
      - "--entrypoints.redis.address=:6379" # Redis endpoint
      - "--entrypoints.websecure.address=:443"
    ports:
      - "6969:8080" # Traefik dashboard
      - "80:80"
      - "443:443" # SSL port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/static.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - mynetwork
  
  postgres:
    image: "postgres:${MASTER_POSTGRES_VERSION}"
    hostname: postgres_server
    environment:
      POSTGRES_DB: ${MASTER_POSTGRES_DB}
      POSTGRES_USER: ${MASTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MASTER_POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${MASTER_POSTGRES_ROOT_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
    driver: overlay
    attachable: true

volumes:
  data: