version: '3.8'
services:
  proxy:
    image: traefik:v3.0.0-beta2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Endpoints setup
      - "--entrypoints.postgres.address=:5432" # PostgreSQL endpoint
      - "--entrypoints.redis.address=:6379" # Redis endpoint
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=thanhduongbdkn2014@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "6969:8080" # Traefik dashboard
      - "5432:5432" # PostgreSQL port
      - "6379:6379" # Redis port
      - "443:443" # SSL port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/letsencrypt:/letsencrypt"
  
  postgres:
    image: "postgres:${MASTER_POSTGRES_VERSION}"
    hostname: postgres_server
    environment:
      POSTGRES_DB: ${MASTER_POSTGRES_DB}
      POSTGRES_USER: ${MASTER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MASTER_POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${MASTER_POSTGRES_ROOT_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - mynetwork
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthy-app.rule=Host(`whoami.rsdn.site`)"
      - "traefik.http.routers.healthy-app.entrypoints=websecure"
      - "traefik.http.services.healthy-app.loadbalancer.server.port=3030"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  mynetwork:
    external: true
    driver: overlay
    attachable: true

volumes:
  data: